[2023-05-21T22:31:27.160+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv3.postgres_to_s3_task manual__2023-05-21T22:31:07.657053+00:00 [queued]>
[2023-05-21T22:31:27.182+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv3.postgres_to_s3_task manual__2023-05-21T22:31:07.657053+00:00 [queued]>
[2023-05-21T22:31:27.184+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-21T22:31:27.185+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-21T22:31:27.185+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-21T22:31:27.216+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): postgres_to_s3_task> on 2023-05-21 22:31:07.657053+00:00
[2023-05-21T22:31:27.227+0000] {standard_task_runner.py:55} INFO - Started process 724 to run task
[2023-05-21T22:31:27.245+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv3', 'postgres_to_s3_task', 'manual__2023-05-21T22:31:07.657053+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv3.py', '--cfg-path', '/tmp/tmpj3uay9ue']
[2023-05-21T22:31:27.246+0000] {standard_task_runner.py:83} INFO - Job 412: Subtask postgres_to_s3_task
[2023-05-21T22:31:27.413+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv3.postgres_to_s3_task manual__2023-05-21T22:31:07.657053+00:00 [running]> on host b03c83f459ca
[2023-05-21T22:31:27.596+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv3
AIRFLOW_CTX_TASK_ID=postgres_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-21T22:31:07.657053+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-21T22:31:07.657053+00:00
[2023-05-21T22:31:27.603+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/postgres_to_s3.py", line 6, in postgres_to_s3
    hook = PostgresHook(postgres_conn_id="postgres_localhost")
NameError: name 'PostgresHook' is not defined
[2023-05-21T22:31:27.619+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv3, task_id=postgres_to_s3_task, execution_date=20230521T223107, start_date=20230521T223127, end_date=20230521T223127
[2023-05-21T22:31:27.648+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 412 for task postgres_to_s3_task (name 'PostgresHook' is not defined; 724)
[2023-05-21T22:31:27.678+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-21T22:31:27.751+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
