[2023-05-15T23:59:08.412+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv2.call_games manual__2023-05-15T23:59:04.917976+00:00 [queued]>
[2023-05-15T23:59:08.422+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv2.call_games manual__2023-05-15T23:59:04.917976+00:00 [queued]>
[2023-05-15T23:59:08.422+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T23:59:08.422+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-15T23:59:08.422+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T23:59:08.438+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): call_games> on 2023-05-15 23:59:04.917976+00:00
[2023-05-15T23:59:08.444+0000] {standard_task_runner.py:55} INFO - Started process 1563 to run task
[2023-05-15T23:59:08.448+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv2', 'call_games', 'manual__2023-05-15T23:59:04.917976+00:00', '--job-id', '1651', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv2.py', '--cfg-path', '/tmp/tmpaval4ivg']
[2023-05-15T23:59:08.449+0000] {standard_task_runner.py:83} INFO - Job 1651: Subtask call_games
[2023-05-15T23:59:08.518+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv2.call_games manual__2023-05-15T23:59:04.917976+00:00 [running]> on host 79f30fa538b6
[2023-05-15T23:59:08.613+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv2
AIRFLOW_CTX_TASK_ID=call_games
AIRFLOW_CTX_EXECUTION_DATE=2023-05-15T23:59:04.917976+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-15T23:59:04.917976+00:00
[2023-05-15T23:59:08.615+0000] {logging_mixin.py:137} INFO - {{ ds }}
[2023-05-15T23:59:08.616+0000] {logging_mixin.py:137} INFO - ['{{ ds }}']
[2023-05-15T23:59:08.616+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_gamesv2.py", line 37, in _call_games
    rearranged_date = datetimeChange(date_call).rearrange_date()
  File "/opt/airflow/dags/functions/functions.py", line 49, in rearrange_date
    month = split_date[1]
IndexError: list index out of range
[2023-05-15T23:59:08.627+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv2, task_id=call_games, execution_date=20230515T235904, start_date=20230515T235908, end_date=20230515T235908
[2023-05-15T23:59:08.640+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1651 for task call_games (list index out of range; 1563)
[2023-05-15T23:59:08.659+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-15T23:59:08.695+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
