[2023-05-22T15:00:04.756+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv2.call_games scheduled__2023-05-21T15:00:00+00:00 [queued]>
[2023-05-22T15:00:04.788+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv2.call_games scheduled__2023-05-21T15:00:00+00:00 [queued]>
[2023-05-22T15:00:04.799+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-22T15:00:04.800+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-22T15:00:04.800+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-22T15:00:04.852+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): call_games> on 2023-05-21 15:00:00+00:00
[2023-05-22T15:00:04.871+0000] {standard_task_runner.py:55} INFO - Started process 135 to run task
[2023-05-22T15:00:04.887+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv2', 'call_games', 'scheduled__2023-05-21T15:00:00+00:00', '--job-id', '418', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv2.py', '--cfg-path', '/tmp/tmp9o9k9832']
[2023-05-22T15:00:04.888+0000] {standard_task_runner.py:83} INFO - Job 418: Subtask call_games
[2023-05-22T15:00:05.045+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv2.call_games scheduled__2023-05-21T15:00:00+00:00 [running]> on host b03c83f459ca
[2023-05-22T15:00:05.279+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv2
AIRFLOW_CTX_TASK_ID=call_games
AIRFLOW_CTX_EXECUTION_DATE=2023-05-21T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-21T15:00:00+00:00
[2023-05-22T15:00:05.284+0000] {logging_mixin.py:137} INFO - 2023-05-22
[2023-05-22T15:00:05.543+0000] {logging_mixin.py:137} INFO - {}
[2023-05-22T15:00:05.543+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_gamesv2.py", line 43, in _call_games
    if games_dict[0]['away_probable_pitcher'].strip()=='':
KeyError: 0
[2023-05-22T15:00:05.562+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv2, task_id=call_games, execution_date=20230521T150000, start_date=20230522T150004, end_date=20230522T150005
[2023-05-22T15:00:05.648+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 418 for task call_games (0; 135)
[2023-05-22T15:00:05.694+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-22T15:00:05.836+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
