[2023-04-23T17:31:04.215+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-23T17:31:01.303404+00:00 [queued]>
[2023-04-23T17:31:04.228+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-23T17:31:01.303404+00:00 [queued]>
[2023-04-23T17:31:04.228+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T17:31:04.229+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-23T17:31:04.229+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T17:31:04.247+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): write_games_s3> on 2023-04-23 17:31:01.303404+00:00
[2023-04-23T17:31:04.254+0000] {standard_task_runner.py:55} INFO - Started process 152 to run task
[2023-04-23T17:31:04.275+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'write_games_s3', 'manual__2023-04-23T17:31:01.303404+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpilwhnrsi']
[2023-04-23T17:31:04.276+0000] {standard_task_runner.py:83} INFO - Job 157: Subtask write_games_s3
[2023-04-23T17:31:04.422+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-23T17:31:01.303404+00:00 [running]> on host f789e77bc70a
[2023-04-23T17:31:04.680+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=write_games_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T17:31:01.303404+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T17:31:01.303404+00:00
[2023-04-23T17:31:04.699+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 52, in write_games
    for k,v in games_data.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2023-04-23T17:31:04.711+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=write_games_s3, execution_date=20230423T173101, start_date=20230423T173104, end_date=20230423T173104
[2023-04-23T17:31:04.737+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 157 for task write_games_s3 ('NoneType' object has no attribute 'items'; 152)
[2023-04-23T17:31:04.750+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T17:31:04.793+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
