[2023-05-23T23:19:43.892+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv3.postgres_to_s3_task manual__2023-05-23T23:19:23.793553+00:00 [queued]>
[2023-05-23T23:19:43.904+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv3.postgres_to_s3_task manual__2023-05-23T23:19:23.793553+00:00 [queued]>
[2023-05-23T23:19:43.904+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T23:19:43.905+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-23T23:19:43.905+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T23:19:43.925+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): postgres_to_s3_task> on 2023-05-23 23:19:23.793553+00:00
[2023-05-23T23:19:43.935+0000] {standard_task_runner.py:55} INFO - Started process 399 to run task
[2023-05-23T23:19:43.944+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv3', 'postgres_to_s3_task', 'manual__2023-05-23T23:19:23.793553+00:00', '--job-id', '505', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv3.py', '--cfg-path', '/tmp/tmpk_hpe_ky']
[2023-05-23T23:19:43.945+0000] {standard_task_runner.py:83} INFO - Job 505: Subtask postgres_to_s3_task
[2023-05-23T23:19:44.027+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv3.postgres_to_s3_task manual__2023-05-23T23:19:23.793553+00:00 [running]> on host b03c83f459ca
[2023-05-23T23:19:44.139+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv3
AIRFLOW_CTX_TASK_ID=postgres_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T23:19:23.793553+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-23T23:19:23.793553+00:00
[2023-05-23T23:19:44.151+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-05-23T23:19:44.159+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/postgres_to_s3.py", line 21, in postgres_to_s3
    logging.info(f'Saved postgres data in text file: games.txt')
NameError: name 'logging' is not defined
[2023-05-23T23:19:44.168+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv3, task_id=postgres_to_s3_task, execution_date=20230523T231923, start_date=20230523T231943, end_date=20230523T231944
[2023-05-23T23:19:44.187+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 505 for task postgres_to_s3_task (name 'logging' is not defined; 399)
[2023-05-23T23:19:44.231+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-23T23:19:44.269+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
