[2023-05-15T23:24:34.749+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv2.check_game_today_task manual__2023-05-15T23:24:28.241064+00:00 [queued]>
[2023-05-15T23:24:34.760+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv2.check_game_today_task manual__2023-05-15T23:24:28.241064+00:00 [queued]>
[2023-05-15T23:24:34.760+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T23:24:34.760+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-15T23:24:34.760+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T23:24:34.778+0000] {taskinstance.py:1303} INFO - Executing <Task(BranchPythonOperator): check_game_today_task> on 2023-05-15 23:24:28.241064+00:00
[2023-05-15T23:24:34.791+0000] {standard_task_runner.py:55} INFO - Started process 866 to run task
[2023-05-15T23:24:34.798+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv2', 'check_game_today_task', 'manual__2023-05-15T23:24:28.241064+00:00', '--job-id', '1618', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv2.py', '--cfg-path', '/tmp/tmp2347bm9u']
[2023-05-15T23:24:34.798+0000] {standard_task_runner.py:83} INFO - Job 1618: Subtask check_game_today_task
[2023-05-15T23:24:34.876+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv2.check_game_today_task manual__2023-05-15T23:24:28.241064+00:00 [running]> on host 79f30fa538b6
[2023-05-15T23:24:34.984+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv2
AIRFLOW_CTX_TASK_ID=check_game_today_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-15T23:24:28.241064+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-15T23:24:28.241064+00:00
[2023-05-15T23:24:34.988+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 210, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_gamesv2.py", line 85, in _check_game_today
    today_date = {{ ds }}
NameError: name 'ds' is not defined
[2023-05-15T23:24:35.002+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv2, task_id=check_game_today_task, execution_date=20230515T232428, start_date=20230515T232434, end_date=20230515T232435
[2023-05-15T23:24:35.031+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1618 for task check_game_today_task (name 'ds' is not defined; 866)
[2023-05-15T23:24:35.087+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-15T23:24:35.222+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
