[2023-03-31T03:13:36.964+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.clean_xcom manual__2023-03-31T03:13:29.117518+00:00 [queued]>
[2023-03-31T03:13:36.975+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.clean_xcom manual__2023-03-31T03:13:29.117518+00:00 [queued]>
[2023-03-31T03:13:36.975+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:13:36.975+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T03:13:36.975+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:13:37.003+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): clean_xcom> on 2023-03-31 03:13:29.117518+00:00
[2023-03-31T03:13:37.009+0000] {standard_task_runner.py:55} INFO - Started process 532 to run task
[2023-03-31T03:13:37.014+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'clean_xcom', 'manual__2023-03-31T03:13:29.117518+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpbizrk4ih']
[2023-03-31T03:13:37.019+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask clean_xcom
[2023-03-31T03:13:37.141+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.clean_xcom manual__2023-03-31T03:13:29.117518+00:00 [running]> on host c73de31c854d
[2023-03-31T03:13:37.311+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=clean_xcom
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T03:13:29.117518+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T03:13:29.117518+00:00
[2023-03-31T03:13:37.313+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/airflow/dags/todays_games.py", line 148, in cleanup_xcom
    session.query(XCom).filter(XCom.dag_id == dag_id).delete()
NameError: name 'XCom' is not defined
[2023-03-31T03:13:37.329+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=clean_xcom, execution_date=20230331T031329, start_date=20230331T031336, end_date=20230331T031337
[2023-03-31T03:13:37.351+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 38 for task clean_xcom (name 'XCom' is not defined; 532)
[2023-03-31T03:13:37.368+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T03:13:37.401+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
