[2023-03-29T23:59:20.502+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.create_postgres_table manual__2023-03-29T23:59:12.558045+00:00 [queued]>
[2023-03-29T23:59:20.519+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.create_postgres_table manual__2023-03-29T23:59:12.558045+00:00 [queued]>
[2023-03-29T23:59:20.519+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T23:59:20.519+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T23:59:20.519+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T23:59:20.540+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-03-29 23:59:12.558045+00:00
[2023-03-29T23:59:20.546+0000] {standard_task_runner.py:55} INFO - Started process 96 to run task
[2023-03-29T23:59:20.552+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'create_postgres_table', 'manual__2023-03-29T23:59:12.558045+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmp0mfkyyqq']
[2023-03-29T23:59:20.553+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask create_postgres_table
[2023-03-29T23:59:20.643+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.create_postgres_table manual__2023-03-29T23:59:12.558045+00:00 [running]> on host 853f67d509ed
[2023-03-29T23:59:20.787+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T23:59:12.558045+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T23:59:12.558045+00:00
[2023-03-29T23:59:20.789+0000] {sql.py:254} INFO - Executing: 
        create table if not exists test_table (
            colA varchar(2),
            colB int,
            colC decimal
        );
    
[2023-03-29T23:59:20.817+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-03-29T23:59:20.822+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=create_postgres_table, execution_date=20230329T235912, start_date=20230329T235920, end_date=20230329T235920
[2023-03-29T23:59:20.843+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 96)
[2023-03-29T23:59:20.889+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T23:59:20.929+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
