[2023-03-31T03:12:25.189+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.clean_xcom manual__2023-03-31T03:12:18.582588+00:00 [queued]>
[2023-03-31T03:12:25.201+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.clean_xcom manual__2023-03-31T03:12:18.582588+00:00 [queued]>
[2023-03-31T03:12:25.201+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:12:25.201+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T03:12:25.201+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:12:25.221+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): clean_xcom> on 2023-03-31 03:12:18.582588+00:00
[2023-03-31T03:12:25.227+0000] {standard_task_runner.py:55} INFO - Started process 498 to run task
[2023-03-31T03:12:25.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'clean_xcom', 'manual__2023-03-31T03:12:18.582588+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpasmdbuil']
[2023-03-31T03:12:25.234+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask clean_xcom
[2023-03-31T03:12:25.311+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.clean_xcom manual__2023-03-31T03:12:18.582588+00:00 [running]> on host c73de31c854d
[2023-03-31T03:12:25.403+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=clean_xcom
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T03:12:18.582588+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T03:12:18.582588+00:00
[2023-03-31T03:12:25.404+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 147, in cleanup_xcom
    session.query(XCom).filter(XCom.dag_id == dag_id).delete()
AttributeError: 'NoneType' object has no attribute 'query'
[2023-03-31T03:12:25.415+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=clean_xcom, execution_date=20230331T031218, start_date=20230331T031225, end_date=20230331T031225
[2023-03-31T03:12:25.430+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 32 for task clean_xcom ('NoneType' object has no attribute 'query'; 498)
[2023-03-31T03:12:25.442+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T03:12:25.465+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
